### PR TITLE
feature: To-Do List

### PR DESCRIPTION
**Pull request by Mindo-Joseph**
#### What does this PR do?
- Creates a To-Do List application
#### Description of Task to be completed?
- Using previous concepts of webpack and the new material on Single Responsibility, create a To-Do List 
#### How should this be manually tested?
- Clone the repo then ```cd``` to the directory you cloned to
- Run ```npm i``` to install dependencies
- Run ```npm run build```
- Open the page on your browser

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello @Mindo-Joseph. Good job on this, :+1: Nice interface. Let's take care of the following:**

:point_right: Remove commented code in mainpage.js

:point_right: Separate the logic for marking todo as done from DOM manipulation.

:point_right: I can't find a list of the projects I created on the app.

:point_right: I should be able to create todos for each project. In other words, a todo should kind of belong to a project, so that it is possible to view all todos that belong to a particular project.

:point_right: You should add a default project to the application.


**_Optional:_**
:point_right: When I mark a todo as done, it moves to the done column :+1: but when I uncheck it, it remains there.

:point_right: Add validations to your forms so that empty objects cannot be created.

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: Require Changes :red_circle: 
### Great Work Implementing Does Changes
- [x] You still missing the default project values
- [x] When I create a task with a wrong date value, the form prevents me from submitting but it's still sending it to the array, once the page refresh I can see does invalid submissions
- [x] When creating a Project, there are no form validations and it's accepting null values
### Once you fixed these issues, submit for a new review 
# :computer: Happy Coding

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Mindo-Joseph, great job with this project :+1: The UI is awesome :smile: Great job fixing the validation outlined by the previous TSE's :slightly_smiling_face: However, some of the issues were not addressed. Kindly check the comments below for more information :100: 
- We currently do not have default values for our and tasks. However, we have one for our projects called `defaults`. As in the screenshot below: Let us implement this change
tk
- I encountered this error trying to create a new task. Kindly check the screenshot below:
mp

Kindly fix these and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by christianotieno — APPROVED** [review]
# Project Approved 🍾 
Hello team 👋 
The project has met all the required changes needed for approval. 👍 
I will go ahead and mark it as complete. Congratulations on the hard work. 🎆  

I wish you all the very best in your next tasks 🥇 
### Happy coding 💻 

#### Christian Otieno (TSE)

**Pull request merged**
